import tkinter as tk
from tkinter import scrolledtext, font
import threading

# Project modules
import main


# This class was generated by ChatGPT-5 mini
# See prompt history in the attached duck.ai text file
# This class should be considered as tech debt, and fixed when possible
class ChatUI(tk.Tk):
    def __init__(self):
        super().__init__()
        # Window setup
        self.title("Chat Interface")
        self.geometry("900x600")
        self.minsize(600, 400)

        # Use a PanedWindow to allow optional right-hand pane (logs).
        # Reason: PanedWindow gives built-in resizing and easy add/remove behavior.
        self.paned = tk.PanedWindow(self, orient=tk.HORIZONTAL, sashrelief=tk.RAISED)
        self.paned.pack(fill=tk.BOTH, expand=True)

        # Left side frame holds the chat history and input
        self.chat_frame = tk.Frame(self.paned)
        self.paned.add(self.chat_frame, minsize=300)  # minsize prevents too-small left pane

        # Top toolbar — currently small, holds the toggle button for logs.
        # Keep toolbar separate so new controls (search, settings) can be added easily.
        toolbar = tk.Frame(self.chat_frame)
        toolbar.pack(fill=tk.X, side=tk.TOP)
        self.toggle_btn = tk.Button(toolbar, text="Toggle Logs", command=self.toggle_logs)
        self.toggle_btn.pack(side=tk.RIGHT, padx=4, pady=4)

        # Chat history container: use ScrolledText for built-in vertical scrolling.
        # We set state to DISABLED when not writing to prevent user edits.
        history_frame = tk.Frame(self.chat_frame)
        history_frame.pack(fill=tk.BOTH, expand=True, padx=6, pady=(0,6))

        self.chat_history = scrolledtext.ScrolledText(history_frame, wrap=tk.WORD, state=tk.DISABLED)
        self.chat_history.pack(fill=tk.BOTH, expand=True)

        # Configure tags now so that alignment/styles are ready when messages are added.
        # Why tags: Text widget supports rich text via tags — we use them for left/right alignment.
        self._configure_history_tags()

        # Bottom input area (expandable)
        input_frame = tk.Frame(self.chat_frame)
        input_frame.pack(fill=tk.X, side=tk.BOTTOM, padx=6, pady=6)

        # Use a dedicated Font object so we can measure text width reliably.
        # Why: measuring average character width enables more accurate wrap calculations.
        self.input_font = font.Font(family="TkDefaultFont")

        # The input is a Text widget (not Entry) so it can hold multiple lines.
        # Start with height=1 and expand the height dynamically as the user types.
        self.input_text = tk.Text(input_frame, height=1, wrap=tk.WORD, font=self.input_font)
        self.input_text.pack(side=tk.LEFT, fill=tk.X, expand=True)

        # Bind events to trigger auto-resize of the input:
        # - <KeyRelease> after typing
        # - <<Paste>> to handle pasted content
        # - <Configure> when widget resizes (window resize or layout changes)
        # Why: keep visual height synced with content and window width.
        self.input_text.bind("<KeyRelease>", self._auto_expand)
        self.input_text.bind("<<Paste>>", self._auto_expand)
        self.input_text.bind("<Configure>", self._auto_expand)
        # Allow Ctrl+Enter to send a message while preserving Enter for newline
        self.input_text.bind("<Control-Return>", self._send_from_ctrl_enter)

        # Send button — calls the same internal send routine used by keyboard shortcut.
        send_btn = tk.Button(input_frame, text="Send", width=10, command=self._send_message)
        send_btn.pack(side=tk.RIGHT, padx=(6,0))

        # Right-side log panel (kept separate so it can be added/removed dynamically)
        # We keep it in a Frame that can be added to the PanedWindow when shown.
        self.log_frame = tk.Frame(self.paned, width=250)
        self.log_visible = False
        self.logs = scrolledtext.ScrolledText(self.log_frame, wrap=tk.WORD, state=tk.DISABLED, width=30)
        self.logs.pack(fill=tk.BOTH, expand=True, padx=4, pady=4)

        # Auto-expand limits: min and max number of visible lines in the input box.
        # Rationale: avoid the input growing indefinitely and pushing the history offscreen.
        self.min_input_lines = 1
        self.max_input_lines = 8
        # Track last applied line count to avoid unnecessary re-layouts
        self._last_line_count = None

        # Add a few initial lines to demonstrate usage. Use public append methods.
        self.append_history_system("System: Chat initialized.")
        self.append_log("Log: UI started.")

    # ---------------------
    # Public API
    # ---------------------

    def toggle_logs(self):
        """
        Show or hide the right-hand log panel.
        Why public: other parts of the application may want to toggle logs programmatically.
        Implementation note: PanedWindow.forget removes the widget but preserves its internal Frame,
        so when we add it back the content remains.
        """
        if self.log_visible:
            try:
                self.paned.forget(self.log_frame)
            except Exception:
                # ignore errors during teardown (defensive)
                pass
            self.log_visible = False
        else:
            self.paned.add(self.log_frame, minsize=150)
            self.log_visible = True

    def append_history_user(self, text):
        """
        Append a user message to the main chat area; right-aligned.
        Public because external message-handlers or network code will call this.
        """
        self._append_history(text, tag="user")

    def append_history_system(self, text):
        """
        Append a system message to the main chat area; left-aligned.
        Public for use by system events or server messages.
        """
        self._append_history(text, tag="system")

    def append_log(self, text):
        """
        Append a line to the log panel (public).
        Logs persist whether or not the panel is visible.
        """
        self.logs.configure(state=tk.NORMAL)
        self.logs.insert(tk.END, text + "\n")
        self.logs.see(tk.END)
        self.logs.configure(state=tk.DISABLED)

    def send_message(self):
        """
        Public wrapper to trigger a send programmatically.
        Useful for automated tests or external hotkeys.
        """
        self._send_message()
        

    # ---------------------
    # Internal helpers
    # ---------------------

    def _configure_history_tags(self):
        """
        Configure tags on the chat_history Text widget for alignment and simple styling.
        Rationale:
        - Text widget applies justification per-paragraph; tags make it easy to apply left/right
          alignment to entire inserted messages.
        - We use margins to create a 'bubble' column (not pixel-perfect bubble shapes but simple
          separation).
        """
        # Left-aligned system messages: small left margin, bigger right margin to avoid full-width text
        self.chat_history.tag_configure("system", justify="left", lmargin1=6, lmargin2=6, rmargin=50)
        # Right-aligned user messages: larger left margin to push text toward the right edge
        self.chat_history.tag_configure("user", justify="right", lmargin1=50, lmargin2=6, rmargin=6)
        # Optional visual bubble backgrounds to differentiate messages
        self.chat_history.tag_configure("user_bubble", background="#e1ffc7")
        self.chat_history.tag_configure("system_bubble", background="#ffffff")

    def _append_history(self, text, tag="system"):
        """
        Insert text into chat_history and apply tag(s) for alignment/styling.
        Why do we insert as a single paragraph (ending with newline)? Because Text widget
        applies 'justify' per-paragraph; ensuring a trailing newline causes the whole message
        to be treated as one paragraph.
        """
        self.chat_history.configure(state=tk.NORMAL)

        # Ensure the message ends with one newline so justify applies cleanly.
        if not text.endswith("\n"):
            text = text + "\n"

        # Compute start index for the inserted text to tag the exact range.
        idx_start = self.chat_history.index(tk.END + "-1c")
        self.chat_history.insert(tk.END, text)
        idx_end = self.chat_history.index(tk.END + "-1c")

        # Apply the main alignment tag (user/system)
        self.chat_history.tag_add(tag, idx_start, idx_end)

        # Apply the bubble background tag for a subtle visual difference
        bubble_tag = "user_bubble" if tag == "user" else "system_bubble"
        self.chat_history.tag_add(bubble_tag, idx_start, idx_end)

        # Scroll to end and disable editing again
        self.chat_history.see(tk.END)
        self.chat_history.configure(state=tk.DISABLED)

    def _send_message(self):
        """
        Internal send routine invoked by the Send button or Ctrl+Enter.
        Behavior:
        - Read input_text, ignore if empty/whitespace.
        - Append user message to history (right-aligned).
        - Append a short log entry.
        - Clear input and reset input height.
        Threading note: this must run on the Tkinter main thread. If calling from another
        thread, marshal via event_generate or a queue.
        """
        msg = self.input_text.get("1.0", tk.END).rstrip("\n")
        if not msg.strip():
            return  # do nothing on empty input

        # Use the public append_history_user method so external consumers have a consistent API
        self.append_history_user(msg)
        self.append_log(f'[USER]: "{msg}"')

        # Clear input and shrink it back to minimum lines to preserve space for history
        self.input_text.delete("1.0", tk.END)
        self._set_input_lines(self.min_input_lines)

    # HUMAN WRITTEN:
        # When the user presses send, handle that prompt in the main module
        response = main.handlePrompt(msg)

        # Append the response to the chat window
        self.append_history_system(response)



    def _send_from_ctrl_enter(self, event=None):
        """
        Bound to Ctrl+Enter so users can insert real newlines with Enter and send via Ctrl+Enter.
        Returning 'break' prevents Tkinter from inserting an extra newline after sending.
        """
        self._send_message()
        return "break"

    def _set_input_lines(self, n):
        """
        Set Text widget height in lines. We track the last set value to avoid redundant
        layout updates (which can cause flicker).
        """
        self.input_text.configure(height=n)
        self._last_line_count = n

    def _auto_expand(self, event=None):
        """
        Compute required number of visual lines for the current input content and resize the
        input Text widget accordingly, clamped between min_input_lines and max_input_lines.

        What we measure and why:
        - The Text widget supports word-wrapping, so a long logical line can span multiple visual
          lines. To estimate visual lines we:
          1) Measure the widget pixel width.
          2) Measure average character pixel width for the current font.
          3) Estimate characters-per-line = widget_width_px / avg_char_width.
          4) For each logical line (split by '\n') compute how many wrapped lines it produces.
        - This is an approximation but is far better than purely counting '\n' because it accounts
          for wrapping.
        - We update only when the computed line count changes to avoid excessive layout churn.
        """
        # Get content without the trailing newline Tk inserts
        content = self.input_text.get("1.0", "end-1c")
        if content == "":
            lines = self.min_input_lines
        else:
            # Determine widget pixel width. If it's not realized yet (very small),
            # fall back to an approximate width computed from the widget 'width' config.
            widget_width_px = self.input_text.winfo_width()
            if widget_width_px <= 1:
                try:
                    widget_width_chars = int(self.input_text.cget("width"))
                except Exception:
                    widget_width_chars = 80
                avg_char_width = self.input_font.measure("n") or 7
                widget_width_px = widget_width_chars * avg_char_width

            # Average character width in pixels for the chosen font.
            avg_char_width = max(1, self.input_font.measure("n"))

            # Approximate number of characters that fit in one visual line.
            chars_per_line = max(20, int(widget_width_px / avg_char_width))

            # Count wrapped visual lines by examining each logical line.
            raw_lines = content.split("\n")
            lines = 0
            for rl in raw_lines:
                if rl == "":
                    # Blank logical line still consumes one visual line
                    lines += 1
                else:
                    # integer math to compute wrapped lines: ceil(len / chars_per_line)
                    wrapped = (len(rl) - 1) // chars_per_line + 1
                    lines += wrapped
            lines = max(self.min_input_lines, lines)

        # Clamp to maximum allowed visible lines
        lines = min(lines, self.max_input_lines)

        # Only update the widget if the line count changed to avoid layout thrash.
        if lines != self._last_line_count:
            self._set_input_lines(lines)
            # Ensure the layout and geometry managers update immediately to avoid flicker.
            self.input_text.update_idletasks()




